# Generated by Django 4.2.24 on 2025-09-24 16:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import iabank.core.fields
import iabank.users.models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data/hora de criação do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Data/hora da última atualização')),
                ('email', models.EmailField(help_text='Email corporativo do usuário', max_length=254, verbose_name='email address')),
                ('login_identifier', models.CharField(editable=False, help_text='Identificador global único (tenant + email)', max_length=255, unique=True)),
                ('username', models.CharField(blank=True, help_text='Identificador curto opcional', max_length=150, null=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, help_text='Telefone de contato com DDI/DDI', max_length=32)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('MANAGER', 'Gestor'), ('CONSULTANT', 'Consultor'), ('COLLECTOR', 'Cobrança'), ('FINANCE_MANAGER', 'Gestor Financeiro'), ('FINANCE_ANALYST', 'Analista Financeiro'), ('COMPLIANCE_MANAGER', 'Gestor de Compliance')], default='MANAGER', help_text='Papel do usuário na hierarquia RBAC', max_length=32)),
                ('is_staff', models.BooleanField(default=False, help_text='Permite acesso ao Django admin')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o usuário está ativo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Data de cadastro do usuário')),
                ('mfa_enabled', models.BooleanField(default=False, help_text='Indica se MFA está habilitado para o usuário')),
                ('mfa_secret', iabank.core.fields.EncryptedCharField(blank=True, help_text='Segredo TOTP criptografado')),
                ('tenant_locked', models.BooleanField(default=False, editable=False, help_text='Controle interno para impedir troca de tenant')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'users',
            },
            managers=[
                ('objects', iabank.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Data/hora de criação do registro')),
                ('email', models.EmailField(help_text='Email corporativo do usuário', max_length=254, verbose_name='email address')),
                ('login_identifier', models.CharField(db_index=True, editable=False, help_text='Identificador global único (tenant + email)', max_length=255)),
                ('username', models.CharField(blank=True, help_text='Identificador curto opcional', max_length=150, null=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, help_text='Telefone de contato com DDI/DDI', max_length=32)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('MANAGER', 'Gestor'), ('CONSULTANT', 'Consultor'), ('COLLECTOR', 'Cobrança'), ('FINANCE_MANAGER', 'Gestor Financeiro'), ('FINANCE_ANALYST', 'Analista Financeiro'), ('COMPLIANCE_MANAGER', 'Gestor de Compliance')], default='MANAGER', help_text='Papel do usuário na hierarquia RBAC', max_length=32)),
                ('is_staff', models.BooleanField(default=False, help_text='Permite acesso ao Django admin')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o usuário está ativo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Data de cadastro do usuário')),
                ('mfa_enabled', models.BooleanField(default=False, help_text='Indica se MFA está habilitado para o usuário')),
                ('mfa_secret', iabank.core.fields.EncryptedCharField(blank=True, help_text='Segredo TOTP criptografado')),
                ('tenant_locked', models.BooleanField(default=False, editable=False, help_text='Controle interno para impedir troca de tenant')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Usuário',
                'verbose_name_plural': 'historical Usuários',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalConsultant',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Data/hora de criação do registro')),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Taxa de comissão aplicada aos empréstimos originados', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('commission_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo acumulado de comissões do consultor', max_digits=15)),
                ('bank_account', iabank.core.fields.EncryptedCharField(blank=True, help_text='Conta bancária criptografada para repasse de comissões')),
                ('is_active_for_loans', models.BooleanField(default=True, help_text='Indica se o consultor pode originar novos empréstimos')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário associado ao consultor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Consultor',
                'verbose_name_plural': 'historical Consultores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data/hora de criação do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Data/hora da última atualização')),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Taxa de comissão aplicada aos empréstimos originados', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('commission_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo acumulado de comissões do consultor', max_digits=15)),
                ('bank_account', iabank.core.fields.EncryptedCharField(blank=True, help_text='Conta bancária criptografada para repasse de comissões')),
                ('is_active_for_loans', models.BooleanField(default=True, help_text='Indica se o consultor pode originar novos empréstimos')),
                ('user', models.OneToOneField(help_text='Usuário associado ao consultor', on_delete=django.db.models.deletion.CASCADE, related_name='consultant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultor',
                'verbose_name_plural': 'Consultores',
                'db_table': 'users_consultants',
                'indexes': [models.Index(fields=['tenant_id', 'user'], name='consultants_tenant_user_idx'), models.Index(fields=['tenant_id', 'is_active_for_loans'], name='consultants_tenant_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='consultant',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'user'), name='consultants_unique_tenant_user'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant_id', 'email'], name='users_tenant_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant_id', 'role'], name='users_tenant_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'email'), name='users_unique_tenant_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'username'), name='users_unique_tenant_username'),
        ),
    ]
