[tool:pytest]
DJANGO_SETTINGS_MODULE = backend.src.iabank.settings
python_files = tests.py test_*.py *_tests.py
testpaths = backend/src tests/integration
addopts = --reuse-db --nomigrations --strict-markers --strict-config --cov --cov-report=term-missing --cov-report=html --cov-fail-under=90
django_find_project = false