# Generated by Django 4.2.24 on 2025-09-24 16:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import iabank.core.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data/hora de criação do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Data/hora da última atualização')),
                ('bank_code', models.CharField(help_text='Código do banco conforme tabela Bacen', max_length=10)),
                ('bank_name', models.CharField(help_text='Nome do banco', max_length=100)),
                ('agency', iabank.core.fields.EncryptedCharField(help_text='Número da agência bancária')),
                ('account_number', iabank.core.fields.EncryptedCharField(help_text='Número da conta bancária')),
                ('account_type', models.CharField(choices=[('CHECKING', 'Conta corrente'), ('SAVINGS', 'Conta poupança'), ('INVESTMENT', 'Conta investimento')], default='CHECKING', help_text='Tipo da conta bancária', max_length=15)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo atual da conta', max_digits=15)),
                ('is_active', models.BooleanField(default=True, help_text='Indica se a conta está ativa para movimentações')),
                ('is_main', models.BooleanField(default=False, help_text='Define se a conta é a principal do tenant')),
                ('account_identifier_hash', models.CharField(editable=False, help_text='Hash do identificador único da conta', max_length=64)),
            ],
            options={
                'db_table': 'finance_bank_accounts',
                'ordering': ['bank_code', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data/hora de criação do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Data/hora da última atualização')),
                ('code', models.CharField(help_text='Codigo interno do centro de custo', max_length=20)),
                ('name', models.CharField(help_text='Nome do centro de custo', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descricao opcional')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o centro esta ativo')),
            ],
            options={
                'db_table': 'finance_cost_centers',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data/hora de criação do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Data/hora da última atualização')),
                ('type', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa')], help_text='Tipo da transação (receita/ despesa)', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor da transação', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(help_text='Descrição breve da transação', max_length=255)),
                ('reference_date', models.DateField(help_text='Data de competência da transação')),
                ('due_date', models.DateField(blank=True, help_text='Data de vencimento (para despesas futuras)', null=True)),
                ('payment_date', models.DateField(blank=True, help_text='Data de pagamento', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('CANCELLED', 'Cancelado')], default='PENDING', help_text='Status atual da transação', max_length=12)),
                ('document_number', models.CharField(blank=True, help_text='Documento de referência (NF, recibo, etc)', max_length=50)),
            ],
            options={
                'db_table': 'finance_financial_transactions',
                'ordering': ['-reference_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBankAccount',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Data/hora de criação do registro')),
                ('bank_code', models.CharField(help_text='Código do banco conforme tabela Bacen', max_length=10)),
                ('bank_name', models.CharField(help_text='Nome do banco', max_length=100)),
                ('agency', iabank.core.fields.EncryptedCharField(help_text='Número da agência bancária')),
                ('account_number', iabank.core.fields.EncryptedCharField(help_text='Número da conta bancária')),
                ('account_type', models.CharField(choices=[('CHECKING', 'Conta corrente'), ('SAVINGS', 'Conta poupança'), ('INVESTMENT', 'Conta investimento')], default='CHECKING', help_text='Tipo da conta bancária', max_length=15)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo atual da conta', max_digits=15)),
                ('is_active', models.BooleanField(default=True, help_text='Indica se a conta está ativa para movimentações')),
                ('is_main', models.BooleanField(default=False, help_text='Define se a conta é a principal do tenant')),
                ('account_identifier_hash', models.CharField(editable=False, help_text='Hash do identificador único da conta', max_length=64)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical bank account',
                'verbose_name_plural': 'historical bank accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCostCenter',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Data/hora de criação do registro')),
                ('code', models.CharField(help_text='Codigo interno do centro de custo', max_length=20)),
                ('name', models.CharField(help_text='Nome do centro de custo', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descricao opcional')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o centro esta ativo')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical cost center',
                'verbose_name_plural': 'historical cost centers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFinancialTransaction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Data/hora de criação do registro')),
                ('type', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa')], help_text='Tipo da transação (receita/ despesa)', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor da transação', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(help_text='Descrição breve da transação', max_length=255)),
                ('reference_date', models.DateField(help_text='Data de competência da transação')),
                ('due_date', models.DateField(blank=True, help_text='Data de vencimento (para despesas futuras)', null=True)),
                ('payment_date', models.DateField(blank=True, help_text='Data de pagamento', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('CANCELLED', 'Cancelado')], default='PENDING', help_text='Status atual da transação', max_length=12)),
                ('document_number', models.CharField(blank=True, help_text='Documento de referência (NF, recibo, etc)', max_length=50)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical financial transaction',
                'verbose_name_plural': 'historical financial transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPaymentCategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Data/hora de criação do registro')),
                ('name', models.CharField(help_text='Nome da categoria', max_length=100)),
                ('type', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa'), ('BOTH', 'Ambos')], help_text='Tipo da categoria', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Indica se a categoria esta ativa')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical payment category',
                'verbose_name_plural': 'historical payment categorys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSupplier',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Data/hora de criação do registro')),
                ('document_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], help_text='Tipo de documento (CPF/CNPJ)', max_length=5)),
                ('document', iabank.core.fields.EncryptedCharField(help_text='Documento do fornecedor armazenado de forma criptografada')),
                ('document_hash', models.CharField(editable=False, help_text='Hash do documento para garantir unicidade', max_length=64)),
                ('name', iabank.core.fields.EncryptedCharField(help_text='Nome ou razao social do fornecedor')),
                ('email', iabank.core.fields.EncryptedEmailField(blank=True, help_text='Email de contato do fornecedor')),
                ('phone', iabank.core.fields.EncryptedCharField(blank=True, help_text='Telefone de contato do fornecedor')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o fornecedor esta ativo')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical supplier',
                'verbose_name_plural': 'historical suppliers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data/hora de criação do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Data/hora da última atualização')),
                ('name', models.CharField(help_text='Nome da categoria', max_length=100)),
                ('type', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa'), ('BOTH', 'Ambos')], help_text='Tipo da categoria', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Indica se a categoria esta ativa')),
            ],
            options={
                'db_table': 'finance_payment_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data/hora de criação do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Data/hora da última atualização')),
                ('document_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], help_text='Tipo de documento (CPF/CNPJ)', max_length=5)),
                ('document', iabank.core.fields.EncryptedCharField(help_text='Documento do fornecedor armazenado de forma criptografada')),
                ('document_hash', models.CharField(editable=False, help_text='Hash do documento para garantir unicidade', max_length=64)),
                ('name', iabank.core.fields.EncryptedCharField(help_text='Nome ou razao social do fornecedor')),
                ('email', iabank.core.fields.EncryptedEmailField(blank=True, help_text='Email de contato do fornecedor')),
                ('phone', iabank.core.fields.EncryptedCharField(blank=True, help_text='Telefone de contato do fornecedor')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o fornecedor esta ativo')),
            ],
            options={
                'db_table': 'finance_suppliers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant_id', 'is_active'], name='fin_supplier_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'document_hash'), name='fin_supplier_unique_document'),
        ),
        migrations.AddIndex(
            model_name='paymentcategory',
            index=models.Index(fields=['tenant_id', 'type'], name='fin_paycat_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcategory',
            index=models.Index(fields=['tenant_id', 'is_active'], name='fin_paycat_tenant_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentcategory',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'name'), name='fin_paycat_unique_name_per_tenant'),
        ),
    ]
