# Generated by Django 4.2.24 on 2025-09-24 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupplier',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpaymentcategory',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfinancialtransaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Conta bancária utilizada na transação', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='historicalfinancialtransaction',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Categoria de classificação', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.paymentcategory'),
        ),
        migrations.AddField(
            model_name='historicalfinancialtransaction',
            name='cost_center',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Centro de custo associado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.costcenter'),
        ),
        migrations.AddField(
            model_name='historicalfinancialtransaction',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfinancialtransaction',
            name='installment',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Parcela associada (para receitas)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.installment'),
        ),
        migrations.AddField(
            model_name='historicalfinancialtransaction',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Fornecedor associado (para despesas)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.supplier'),
        ),
        migrations.AddField(
            model_name='historicalcostcenter',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbankaccount',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='bank_account',
            field=models.ForeignKey(help_text='Conta bancária utilizada na transação', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='category',
            field=models.ForeignKey(help_text='Categoria de classificação', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.paymentcategory'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='cost_center',
            field=models.ForeignKey(blank=True, help_text='Centro de custo associado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.costcenter'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='installment',
            field=models.ForeignKey(blank=True, help_text='Parcela associada (para receitas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='operations.installment'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Fornecedor associado (para despesas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.supplier'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['tenant_id', 'is_active'], name='fin_cost_center_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'code'), name='fin_cost_center_unique_code'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['tenant_id', 'bank_code'], name='fin_bank_tenant_bank_code_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['tenant_id', 'is_active'], name='fin_bank_tenant_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'account_identifier_hash'), name='fin_bank_unique_account_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('tenant_id',), name='fin_bank_unique_main_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['tenant_id', 'type'], name='fin_trans_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['tenant_id', 'status'], name='fin_trans_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['tenant_id', 'reference_date'], name='fin_trans_tenant_reference_idx'),
        ),
    ]
