# Generated by Django 4.2.26 on 2025-11-15 21:48

import backend.apps.tenancy.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0026_encrypt_theme_payload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        migrations.AlterModelManagers(
            name='tenantthemetoken',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
    ]
