# Generated by Django 4.2.26 on 2025-11-27 19:54

import backend.apps.tenancy.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0028_seed_models'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='budgetratelimit',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='evidenceworm',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='seedbatch',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='seedcheckpoint',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='seeddataset',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='seedidempotency',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='seedprofile',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='seedqueue',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='seedrbac',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='seedrun',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterField(
            model_name='budgetratelimit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='evidenceworm',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='seedbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='seedcheckpoint',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='seeddataset',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='seedidempotency',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='seedprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='seedrbac',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='seedrun',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
    ]
