# Generated by Django 4.2.24 on 2025-09-17 22:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import iabank.core.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data/hora de criação do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Data/hora da última atualização')),
                ('document_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], help_text='Tipo de documento utilizado pelo cliente', max_length=5)),
                ('document', iabank.core.fields.EncryptedCharField(help_text='Documento do cliente armazenado de forma criptografada')),
                ('document_hash', models.CharField(editable=False, help_text='Hash do documento para garantir unicidade por tenant', max_length=64)),
                ('name', iabank.core.fields.EncryptedCharField(help_text='Nome completo ou razão social do cliente')),
                ('email', iabank.core.fields.EncryptedEmailField(help_text='Email de contato do cliente')),
                ('phone', iabank.core.fields.EncryptedCharField(blank=True, help_text='Telefone principal do cliente')),
                ('birth_date', models.DateField(blank=True, help_text='Data de nascimento (para pessoas físicas)', null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('OTHER', 'Outro')], help_text='Gênero informado pelo cliente', max_length=10)),
                ('profession', iabank.core.fields.EncryptedCharField(blank=True, help_text='Profissão ou cargo principal')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, help_text='Renda mensal declarada pelo cliente', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('credit_score', models.IntegerField(blank=True, help_text='Score de crédito (0-1000)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('score_last_updated', models.DateTimeField(blank=True, help_text='Data/hora da última atualização do score', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o cliente está ativo para operações')),
            ],
            options={
                'db_table': 'customers_customers',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCustomer',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Data/hora de criação do registro')),
                ('document_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], help_text='Tipo de documento utilizado pelo cliente', max_length=5)),
                ('document', iabank.core.fields.EncryptedCharField(help_text='Documento do cliente armazenado de forma criptografada')),
                ('document_hash', models.CharField(editable=False, help_text='Hash do documento para garantir unicidade por tenant', max_length=64)),
                ('name', iabank.core.fields.EncryptedCharField(help_text='Nome completo ou razão social do cliente')),
                ('email', iabank.core.fields.EncryptedEmailField(help_text='Email de contato do cliente')),
                ('phone', iabank.core.fields.EncryptedCharField(blank=True, help_text='Telefone principal do cliente')),
                ('birth_date', models.DateField(blank=True, help_text='Data de nascimento (para pessoas físicas)', null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('OTHER', 'Outro')], help_text='Gênero informado pelo cliente', max_length=10)),
                ('profession', iabank.core.fields.EncryptedCharField(blank=True, help_text='Profissão ou cargo principal')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, help_text='Renda mensal declarada pelo cliente', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('credit_score', models.IntegerField(blank=True, help_text='Score de crédito (0-1000)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('score_last_updated', models.DateTimeField(blank=True, help_text='Data/hora da última atualização do score', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o cliente está ativo para operações')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical customer',
                'verbose_name_plural': 'historical customers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
