# Generated by Django 4.2.24 on 2025-09-24 16:28

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data/hora de criação do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Data/hora da última atualização')),
                ('type', models.CharField(choices=[('RESIDENTIAL', 'Residencial'), ('COMMERCIAL', 'Comercial'), ('CORRESPONDENCE', 'Correspondência')], default='RESIDENTIAL', help_text='Tipo de endereço', max_length=20)),
                ('street', models.CharField(help_text='Logradouro', max_length=255)),
                ('number', models.CharField(help_text='Número', max_length=20)),
                ('complement', models.CharField(blank=True, help_text='Complemento', max_length=100)),
                ('neighborhood', models.CharField(help_text='Bairro', max_length=100)),
                ('city', models.CharField(help_text='Cidade', max_length=100)),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='UF do endereço', max_length=2)),
                ('zipcode', models.CharField(help_text='CEP no formato 00000-000', max_length=9)),
                ('is_primary', models.BooleanField(default=False, help_text='Indica se é o endereço principal do cliente')),
            ],
            options={
                'db_table': 'customers_addresses',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAddress',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Data/hora de criação do registro')),
                ('type', models.CharField(choices=[('RESIDENTIAL', 'Residencial'), ('COMMERCIAL', 'Comercial'), ('CORRESPONDENCE', 'Correspondência')], default='RESIDENTIAL', help_text='Tipo de endereço', max_length=20)),
                ('street', models.CharField(help_text='Logradouro', max_length=255)),
                ('number', models.CharField(help_text='Número', max_length=20)),
                ('complement', models.CharField(blank=True, help_text='Complemento', max_length=100)),
                ('neighborhood', models.CharField(help_text='Bairro', max_length=100)),
                ('city', models.CharField(help_text='Cidade', max_length=100)),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='UF do endereço', max_length=2)),
                ('zipcode', models.CharField(help_text='CEP no formato 00000-000', max_length=9)),
                ('is_primary', models.BooleanField(default=False, help_text='Indica se é o endereço principal do cliente')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, help_text='Cliente ao qual o endereço pertence', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer')),
            ],
            options={
                'verbose_name': 'historical address',
                'verbose_name_plural': 'historical addresss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
