# Generated by Django 4.2.24 on 2025-09-24 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_address_historicaladdress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaladdress',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(help_text='Cliente ao qual o endereço pertence', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['tenant_id', 'customer'], name='cust_addr_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['tenant_id', 'zipcode'], name='cust_addr_zipcode_idx'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('tenant_id', 'customer'), name='cust_addr_primary_unique'),
        ),
    ]
