# Generated by Django 4.2.23 on 2025-09-13 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique tenant identifier', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Company name', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('cnpj', models.CharField(help_text='Company CNPJ (formatted: XX.XXX.XXX/XXXX-XX)', max_length=18, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the tenant is active and can access the platform')),
                ('subscription_plan', models.CharField(choices=[('BASIC', 'Basic'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='BASIC', help_text='Current subscription plan', max_length=50)),
                ('max_users', models.PositiveIntegerField(default=5, help_text='Maximum number of users allowed')),
                ('max_loans_per_month', models.PositiveIntegerField(default=100, help_text='Maximum loans that can be created per month')),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Full address')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, help_text='State code (e.g., SP)', max_length=2)),
                ('zip_code', models.CharField(blank=True, help_text='CEP', max_length=9)),
                ('max_interest_rate', models.DecimalField(decimal_places=2, default=12.0, help_text='Maximum interest rate allowed (compliance with usury law)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_tenant',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='core_tenant_is_acti_99418a_idx'), models.Index(fields=['cnpj'], name='core_tenant_cnpj_dc1d24_idx'), models.Index(fields=['slug'], name='core_tenant_slug_bb8545_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTenant',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique tenant identifier')),
                ('name', models.CharField(help_text='Company name', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100)),
                ('cnpj', models.CharField(db_index=True, help_text='Company CNPJ (formatted: XX.XXX.XXX/XXXX-XX)', max_length=18)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the tenant is active and can access the platform')),
                ('subscription_plan', models.CharField(choices=[('BASIC', 'Basic'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='BASIC', help_text='Current subscription plan', max_length=50)),
                ('max_users', models.PositiveIntegerField(default=5, help_text='Maximum number of users allowed')),
                ('max_loans_per_month', models.PositiveIntegerField(default=100, help_text='Maximum loans that can be created per month')),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Full address')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, help_text='State code (e.g., SP)', max_length=2)),
                ('zip_code', models.CharField(blank=True, help_text='CEP', max_length=9)),
                ('max_interest_rate', models.DecimalField(decimal_places=2, default=12.0, help_text='Maximum interest rate allowed (compliance with usury law)', max_digits=5)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tenant',
                'verbose_name_plural': 'historical tenants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
