# Generated by Django 4.2.23 on 2025-09-14 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='ID do tenant para isolamento de dados', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data/hora de criação do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Data/hora da última atualização')),
                ('name', models.CharField(help_text='Nome da empresa', max_length=200)),
                ('cnpj', models.CharField(db_index=True, help_text='CNPJ da empresa (formatado)', max_length=18, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Tenant ativo na plataforma')),
                ('created_by', models.CharField(blank=True, help_text='Usuário que criou o tenant', max_length=200)),
                ('settings', models.JSONField(default=dict, help_text='Configurações específicas do tenant (taxa máxima, etc)')),
            ],
            options={
                'db_table': 'core_tenants',
                'indexes': [models.Index(fields=['cnpj'], name='core_tenants_cnpj_idx'), models.Index(fields=['is_active'], name='core_tenants_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTenant',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='ID do tenant para isolamento de dados', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Data/hora de criação do registro')),
                ('name', models.CharField(help_text='Nome da empresa', max_length=200)),
                ('cnpj', models.CharField(db_index=True, help_text='CNPJ da empresa (formatado)', max_length=18)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Tenant ativo na plataforma')),
                ('created_by', models.CharField(blank=True, help_text='Usuário que criou o tenant', max_length=200)),
                ('settings', models.JSONField(default=dict, help_text='Configurações específicas do tenant (taxa máxima, etc)')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tenant',
                'verbose_name_plural': 'historical tenants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
