# Generated by Django 4.2.23 on 2025-09-17 17:16

import re
import iabank.core.models
from django.db import migrations, models
from django.utils.text import slugify


def populate_tenant_data(apps, schema_editor):
    Tenant = apps.get_model("core", "Tenant")
    HistoricalTenant = apps.get_model("core", "HistoricalTenant")

    for tenant in Tenant.objects.all():
        normalized_document = re.sub(r"\D", "", tenant.document or "")
        base_slug = slugify(tenant.slug or tenant.name or tenant.id.hex)
        if not base_slug:
            base_slug = tenant.id.hex[:8]
        base_slug = base_slug[:60]
        candidate = base_slug
        suffix = 2
        while Tenant.objects.exclude(pk=tenant.pk).filter(slug=candidate).exists():
            suffix_str = f"-{suffix}"
            candidate = f"{base_slug[: 60 - len(suffix_str)]}{suffix_str}"
            suffix += 1

        domain = (tenant.domain or f"{candidate}.dev.iabank.local").lower()

        Tenant.objects.filter(pk=tenant.pk).update(
            document=normalized_document,
            slug=candidate,
            domain=domain,
        )
        HistoricalTenant.objects.filter(id=tenant.id).update(
            document=normalized_document,
            slug=candidate,
            domain=domain,
        )


def reverse_populate_tenant_data(apps, schema_editor):
    # No reverse operation required for data normalization.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DO $$ BEGIN IF to_regclass('public.core_tenant') IS NOT NULL AND to_regclass('public.core_tenants') IS NULL THEN ALTER TABLE core_tenant RENAME TO core_tenants; END IF; END $$;",
            reverse_sql="DO $$ BEGIN IF to_regclass('public.core_tenants') IS NOT NULL AND to_regclass('public.core_tenant') IS NULL THEN ALTER TABLE core_tenants RENAME TO core_tenant; END IF; END $$;",
        ),
        migrations.RenameField(
            model_name="tenant",
            old_name="cnpj",
            new_name="document",
        ),
        migrations.RenameField(
            model_name="historicaltenant",
            old_name="cnpj",
            new_name="document",
        ),
        migrations.AddField(
            model_name="tenant",
            name="slug",
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True, help_text="Identificador curto usado em subdomínios"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="domain",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, help_text="Domínio customizado do tenant (opcional)"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, help_text="Email principal de contato"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="phone_number",
            field=models.CharField(blank=True, max_length=32, help_text="Telefone comercial do tenant"),
        ),
        migrations.AddField(
            model_name="historicaltenant",
            name="slug",
            field=models.SlugField(blank=True, max_length=60, null=True, help_text="Identificador curto usado em subdomínios"),
        ),
        migrations.AddField(
            model_name="historicaltenant",
            name="domain",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, help_text="Domínio customizado do tenant (opcional)"),
        ),
        migrations.AddField(
            model_name="historicaltenant",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, help_text="Email principal de contato"),
        ),
        migrations.AddField(
            model_name="historicaltenant",
            name="phone_number",
            field=models.CharField(blank=True, max_length=32, help_text="Telefone comercial do tenant"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="document",
            field=models.CharField(db_index=True, help_text="CNPJ da empresa somente com dígitos", max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name="historicaltenant",
            name="document",
            field=models.CharField(db_index=True, help_text="CNPJ da empresa somente com dígitos", max_length=14),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="name",
            field=models.CharField(help_text="Nome legal da empresa", max_length=255),
        ),
        migrations.AlterField(
            model_name="historicaltenant",
            name="name",
            field=models.CharField(help_text="Nome legal da empresa", max_length=255),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="created_by",
            field=models.CharField(blank=True, help_text="Usuário responsável pela criação", max_length=200),
        ),
        migrations.AlterField(
            model_name="historicaltenant",
            name="created_by",
            field=models.CharField(blank=True, help_text="Usuário responsável pela criação", max_length=200),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="settings",
            field=models.JSONField(default=iabank.core.models._default_tenant_settings, help_text="Configurações específicas do tenant"),
        ),
        migrations.AlterField(
            model_name="historicaltenant",
            name="settings",
            field=models.JSONField(default=iabank.core.models._default_tenant_settings, help_text="Configurações específicas do tenant"),
        ),
        migrations.RemoveIndex(
            model_name="tenant",
            name="core_tenants_cnpj_idx",
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["document"], name="core_tenants_document_idx"),
        ),
        migrations.RunPython(populate_tenant_data, reverse_populate_tenant_data),
        migrations.AlterField(
            model_name="tenant",
            name="slug",
            field=models.SlugField(blank=True, max_length=60, unique=True, help_text="Identificador curto usado em subdomínios"),
        ),
        migrations.AlterField(
            model_name="historicaltenant",
            name="slug",
            field=models.SlugField(blank=True, db_index=True, help_text="Identificador curto usado em subdomínios", max_length=60),
        ),
    ]
