# Generated by Django 4.2.24 on 2025-09-24 16:28

from django.db import migrations, models


def _sync_tenant_ids(apps, schema_editor):
    Tenant = apps.get_model('core', 'Tenant')
    HistoricalTenant = apps.get_model('core', 'HistoricalTenant')

    for tenant in Tenant.objects.filter(tenant_id__isnull=True):
        Tenant.objects.filter(pk=tenant.pk).update(tenant_id=tenant.id)

    for history in HistoricalTenant.objects.filter(tenant_id__isnull=True):
        HistoricalTenant.objects.filter(history_id=history.history_id).update(tenant_id=history.id)


def _noop(apps, schema_editor):
    # Nenhuma ação necessária na reversão.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_update_tenant_model'),
    ]

    operations = [
        migrations.RunPython(_sync_tenant_ids, _noop),
        migrations.AlterField(
            model_name='historicaltenant',
            name='tenant_id',
            field=models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenant_id',
            field=models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados'),
        ),
    ]
