// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetHealthCheckData, GetHealthCheckResponses, GetTenantThemeData, GetTenantThemeResponses, GetTenantThemeErrors, RegisterFeatureScaffoldData, RegisterFeatureScaffoldResponses, RegisterFeatureScaffoldErrors, ListTenantSuccessMetricsData, ListTenantSuccessMetricsResponses, ListTenantSuccessMetricsErrors, ListDesignSystemStoriesData, ListDesignSystemStoriesResponses, ListDesignSystemStoriesErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check
 * Retorna o status de saúde do serviço de fundação frontend.
 */
export const getHealthCheck = <ThrowOnError extends boolean = false>(options?: Options<GetHealthCheckData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetHealthCheckResponses, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};

/**
 * Recuperar tokens ativos do tenant corrente
 * Retorna o conjunto de tokens fundacionais, semânticos e de componentes aplicados ao tenant corrente. Respeita RLS (Art. XIII) e mascaramento de PII em logs. Respostas incluem ETag para controle de concorrência em caches front-end.
 *
 */
export const getTenantTheme = <ThrowOnError extends boolean = false>(options: Options<GetTenantThemeData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetTenantThemeResponses, GetTenantThemeErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/tenants/{tenantId}/themes/current',
        ...options
    });
};

/**
 * Registrar scaffolding de uma feature FSD
 * Endpoint idempotente responsável por registrar, validar e auditar o scaffolding de uma nova feature FSD. Requer chave de idempotência, executa validações de lint e propaga métricas SC-001/SC-003.
 *
 */
export const registerFeatureScaffold = <ThrowOnError extends boolean = false>(options: Options<RegisterFeatureScaffoldData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RegisterFeatureScaffoldResponses, RegisterFeatureScaffoldErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/tenants/{tenantId}/features/scaffold',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Consultar métricas SC agregadas por tenant
 * Fornece métricas SC-001 a SC-005 agregadas por tenant, alimentadas pelos pipelines CI/CD (Chromatic, Lighthouse, Pact). Resultados mascaram PII e são paginados para relatórios.
 *
 */
export const listTenantSuccessMetrics = <ThrowOnError extends boolean = false>(options: Options<ListTenantSuccessMetricsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ListTenantSuccessMetricsResponses, ListTenantSuccessMetricsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/tenant-metrics/{tenantId}/sc',
        ...options
    });
};

/**
 * Listar stories multi-tenant com status de acessibilidade
 * Disponibiliza stories publicados para consumo por Chromatic/Storybook, com metadados de cobertura visual e auditoria axe-core. Utiliza ETag e paginação.
 *
 */
export const listDesignSystemStories = <ThrowOnError extends boolean = false>(options?: Options<ListDesignSystemStoriesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListDesignSystemStoriesResponses, ListDesignSystemStoriesErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/design-system/stories',
        ...options
    });
};