// This file is auto-generated by @hey-api/openapi-ts

export type ProblemDetails = {
    type: string;
    title: string;
    status: number;
    detail?: string;
    instance?: string;
    traceId: string;
    violations?: Array<{
        field?: string;
        message?: string;
    }>;
};

export type TenantThemeResponse = {
    tenantId: string;
    version: string;
    generatedAt: string;
    /**
     * Tokens agrupados (`foundation`, `semantic`, `component`).
     */
    categories: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
    /**
     * Resumo das medições WCAG (contraste, status).
     */
    wcagReport?: {
        [key: string]: unknown;
    };
};

export type FeatureScaffoldRequest = {
    featureSlug: string;
    initiatedBy: string;
    slices: Array<{
        slice: 'app' | 'pages' | 'features' | 'entities' | 'shared';
        files: Array<{
            path: string;
            /**
             * SHA-256 do arquivo gerado.
             */
            checksum: string;
        }>;
    }>;
    lintCommitHash: string;
    scReferences: Array<string>;
    durationMs?: number;
    /**
     * Campos adicionais (ex.: versão do CLI).
     */
    metadata?: {
        [key: string]: unknown;
    };
};

export type FeatureScaffoldResponse = {
    scaffoldId: string;
    tenantId: string;
    status: 'initiated' | 'linted' | 'tested' | 'published';
    recordedAt: string;
    metrics?: Array<SuccessMetric>;
};

export type SuccessMetric = {
    code: 'SC-001' | 'SC-002' | 'SC-003' | 'SC-004' | 'SC-005';
    value: number;
    collectedAt: string;
    source?: 'ci' | 'chromatic' | 'lighthouse' | 'manual';
};

export type TenantMetricPage = {
    data: Array<SuccessMetric>;
    pagination: Pagination;
};

export type DesignSystemStoryPage = {
    data: Array<DesignSystemStory>;
    pagination: Pagination;
};

export type DesignSystemStory = {
    id: string;
    tenantId?: string | null;
    componentId: string;
    storyId: string;
    tags?: Array<string>;
    coveragePercent: number;
    axeStatus: 'pass' | 'fail' | 'warn';
    chromaticBuild: string;
    storybookUrl?: string;
    updatedAt: string;
};

export type Pagination = {
    page: number;
    perPage: number;
    totalItems: number;
    totalPages: number;
};

/**
 * Identificador do tenant (UUID).
 */
export type TenantIdPath = string;

/**
 * Tenant corrente propagado pelo gateway. Deve coincidir com o `tenantId` da rota.
 *
 */
export type TenantHeader = string;

/**
 * Tenant solicitado; se omitido usa o tenant default do subdomínio. Em desenvolvimento/local sem subdomínio, o fallback é `tenant-default` (configuração de ambiente). Em staging/prod, o subdomínio prevalece e o header é apenas filtro/otimização.
 *
 */
export type TenantHeaderOptional = string;

/**
 * Cabeçalho W3C Trace Context.
 */
export type TraceParent = string;

/**
 * Cabeçalho W3C Trace Context state.
 */
export type TraceState = string;

/**
 * Página solicitada (1-indexed).
 */
export type PageNumber = number;

/**
 * Tamanho da página.
 */
export type PageSize = number;

export type GetHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthCheckResponses = {
    /**
     * OK
     */
    200: {
        status?: string;
    };
};

export type GetHealthCheckResponse = GetHealthCheckResponses[keyof GetHealthCheckResponses];

export type GetTenantThemeData = {
    body?: never;
    headers: {
        /**
         * Tenant corrente propagado pelo gateway. Deve coincidir com o `tenantId` da rota.
         *
         */
        'X-Tenant-Id': string;
        /**
         * Cabeçalho W3C Trace Context.
         */
        traceparent?: string;
        /**
         * Cabeçalho W3C Trace Context state.
         */
        tracestate?: string;
    };
    path: {
        /**
         * Identificador do tenant (UUID).
         */
        tenantId: string;
    };
    query?: never;
    url: '/api/v1/tenants/{tenantId}/themes/current';
};

export type GetTenantThemeErrors = {
    /**
     * Recurso não encontrado.
     */
    404: ProblemDetails;
    /**
     * Rate limiting atingido.
     */
    429: ProblemDetails;
};

export type GetTenantThemeError = GetTenantThemeErrors[keyof GetTenantThemeErrors];

export type GetTenantThemeResponses = {
    /**
     * Tokens retornados com sucesso.
     */
    200: TenantThemeResponse;
};

export type GetTenantThemeResponse = GetTenantThemeResponses[keyof GetTenantThemeResponses];

export type RegisterFeatureScaffoldData = {
    body: FeatureScaffoldRequest;
    headers: {
        /**
         * Tenant corrente propagado pelo gateway. Deve coincidir com o `tenantId` da rota.
         *
         */
        'X-Tenant-Id': string;
        /**
         * Cabeçalho W3C Trace Context.
         */
        traceparent?: string;
        /**
         * Cabeçalho W3C Trace Context state.
         */
        tracestate?: string;
    };
    path: {
        /**
         * Identificador do tenant (UUID).
         */
        tenantId: string;
    };
    query?: never;
    url: '/api/v1/tenants/{tenantId}/features/scaffold';
};

export type RegisterFeatureScaffoldErrors = {
    /**
     * Requisição inválida (erro de validação).
     */
    400: ProblemDetails;
    /**
     * Recurso já existente ou versão desatualizada (ETag).
     */
    409: ProblemDetails;
    /**
     * Erros semânticos (lint, testes) bloqueando publicação.
     */
    422: ProblemDetails;
};

export type RegisterFeatureScaffoldError = RegisterFeatureScaffoldErrors[keyof RegisterFeatureScaffoldErrors];

export type RegisterFeatureScaffoldResponses = {
    /**
     * Scaffolding registrado com sucesso.
     */
    201: FeatureScaffoldResponse;
    /**
     * Scaffolding aceito e em processamento assíncrono.
     */
    202: unknown;
};

export type RegisterFeatureScaffoldResponse = RegisterFeatureScaffoldResponses[keyof RegisterFeatureScaffoldResponses];

export type ListTenantSuccessMetricsData = {
    body?: never;
    headers: {
        /**
         * Tenant corrente propagado pelo gateway. Deve coincidir com o `tenantId` da rota.
         *
         */
        'X-Tenant-Id': string;
        /**
         * Cabeçalho W3C Trace Context.
         */
        traceparent?: string;
        /**
         * Cabeçalho W3C Trace Context state.
         */
        tracestate?: string;
    };
    path: {
        /**
         * Identificador do tenant (UUID).
         */
        tenantId: string;
    };
    query?: {
        /**
         * Página solicitada (1-indexed).
         */
        page?: number;
        /**
         * Tamanho da página.
         */
        per_page?: number;
    };
    url: '/api/v1/tenant-metrics/{tenantId}/sc';
};

export type ListTenantSuccessMetricsErrors = {
    /**
     * Recurso não encontrado.
     */
    404: ProblemDetails;
    /**
     * Rate limiting atingido.
     */
    429: ProblemDetails;
};

export type ListTenantSuccessMetricsError = ListTenantSuccessMetricsErrors[keyof ListTenantSuccessMetricsErrors];

export type ListTenantSuccessMetricsResponses = {
    /**
     * Página de métricas retornada.
     */
    200: TenantMetricPage;
};

export type ListTenantSuccessMetricsResponse = ListTenantSuccessMetricsResponses[keyof ListTenantSuccessMetricsResponses];

export type ListDesignSystemStoriesData = {
    body?: never;
    headers?: {
        /**
         * Tenant solicitado; se omitido usa o tenant default do subdomínio. Em desenvolvimento/local sem subdomínio, o fallback é `tenant-default` (configuração de ambiente). Em staging/prod, o subdomínio prevalece e o header é apenas filtro/otimização.
         *
         */
        'X-Tenant-Id'?: string;
        /**
         * Cabeçalho W3C Trace Context.
         */
        traceparent?: string;
        /**
         * Cabeçalho W3C Trace Context state.
         */
        tracestate?: string;
    };
    path?: never;
    query?: {
        /**
         * Página solicitada (1-indexed).
         */
        page?: number;
        /**
         * Tamanho da página.
         */
        per_page?: number;
        /**
         * Filtrar por componente (`shared/ui/button`).
         */
        componentId?: string;
        /**
         * Filtrar por tag (ex.: `critical`).
         */
        tag?: string;
    };
    url: '/api/v1/design-system/stories';
};

export type ListDesignSystemStoriesErrors = {
    /**
     * Rate limiting atingido.
     */
    429: ProblemDetails;
};

export type ListDesignSystemStoriesError = ListDesignSystemStoriesErrors[keyof ListDesignSystemStoriesErrors];

export type ListDesignSystemStoriesResponses = {
    /**
     * Lista de stories.
     */
    200: DesignSystemStoryPage;
};

export type ListDesignSystemStoriesResponse = ListDesignSystemStoriesResponses[keyof ListDesignSystemStoriesResponses];

export type ClientOptions = {
    baseUrl: 'https://api.iabank.com' | 'https://staging-api.iabank.com' | (string & {});
};