openapi: 3.0.3
info:
  title: Placeholder API
  version: 0.0.1
  description: |
    Baseline mínima utilizada para diffs de contratos da fundação frontend.
  contact:
    name: Frontend Foundation Guild
    email: fe-foundation@iabank.com
servers:
  - url: https://api.placeholder.test
    description: Ambiente placeholder
tags:
  - name: Health
    description: Operações de verificação de integridade do serviço placeholder.
paths:
  /health:
    get:
      tags:
        - Health
      operationId: getHealthCheck
      description: Retorna o status de saúde do serviço de fundação frontend.
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
