# Generated by Django 4.2.24 on 2025-09-24 16:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInstallment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Data/hora de criação do registro')),
                ('sequence', models.PositiveIntegerField(help_text='Número sequencial da parcela dentro do empréstimo')),
                ('due_date', models.DateField(help_text='Data de vencimento da parcela')),
                ('principal_amount', models.DecimalField(decimal_places=2, help_text='Valor principal referente à parcela', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('interest_amount', models.DecimalField(decimal_places=2, help_text='Valor de juros incidente sobre a parcela', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Valor total devido na parcela (principal + juros)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor total pago até o momento', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_date', models.DateField(blank=True, help_text='Data do último pagamento registrado', null=True)),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Multa por atraso aplicada à parcela', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('interest_penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Juros de mora aplicados à parcela', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PARTIALLY_PAID', 'Parcialmente paga'), ('PAID', 'Paga'), ('OVERDUE', 'Em atraso')], default='PENDING', help_text='Status atual da parcela', max_length=20)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical installment',
                'verbose_name_plural': 'historical installments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLoan',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Data/hora de criação do registro')),
                ('principal_amount', models.DecimalField(decimal_places=2, help_text='Valor principal concedido ao cliente', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('interest_rate', models.DecimalField(decimal_places=4, help_text='Taxa de juros mensal aplicada ao empréstimo', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('installments_count', models.PositiveIntegerField(help_text='Quantidade total de parcelas do empréstimo', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('iof_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de IOF calculado para o empréstimo', max_digits=15)),
                ('cet_monthly', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='CET mensal (Custo Efetivo Total)', max_digits=7)),
                ('cet_yearly', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='CET anual (Custo Efetivo Total)', max_digits=7)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor total devido considerando juros e IOF', max_digits=15)),
                ('contract_date', models.DateField(default=django.utils.timezone.localdate, help_text='Data de assinatura do contrato')),
                ('first_due_date', models.DateField(help_text='Data de vencimento da primeira parcela')),
                ('status', models.CharField(choices=[('ANALYSIS', 'Em análise'), ('APPROVED', 'Aprovado'), ('ACTIVE', 'Ativo'), ('FINISHED', 'Finalizado'), ('COLLECTION', 'Em cobrança'), ('CANCELLED', 'Cancelado')], default='ANALYSIS', help_text='Status atual do empréstimo', max_length=15)),
                ('regret_deadline', models.DateField(blank=True, help_text='Prazo legal para arrependimento (7 dias)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Observações adicionais sobre o empréstimo')),
                ('version', models.PositiveIntegerField(default=1, help_text='Controle de concorrência otimista')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical loan',
                'verbose_name_plural': 'historical loans',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data/hora de criação do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Data/hora da última atualização')),
                ('sequence', models.PositiveIntegerField(help_text='Número sequencial da parcela dentro do empréstimo')),
                ('due_date', models.DateField(help_text='Data de vencimento da parcela')),
                ('principal_amount', models.DecimalField(decimal_places=2, help_text='Valor principal referente à parcela', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('interest_amount', models.DecimalField(decimal_places=2, help_text='Valor de juros incidente sobre a parcela', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Valor total devido na parcela (principal + juros)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor total pago até o momento', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_date', models.DateField(blank=True, help_text='Data do último pagamento registrado', null=True)),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Multa por atraso aplicada à parcela', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('interest_penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Juros de mora aplicados à parcela', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PARTIALLY_PAID', 'Parcialmente paga'), ('PAID', 'Paga'), ('OVERDUE', 'Em atraso')], default='PENDING', help_text='Status atual da parcela', max_length=20)),
            ],
            options={
                'db_table': 'operations_installments',
                'ordering': ['due_date', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='ID do tenant para isolamento de dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data/hora de criação do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Data/hora da última atualização')),
                ('principal_amount', models.DecimalField(decimal_places=2, help_text='Valor principal concedido ao cliente', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('interest_rate', models.DecimalField(decimal_places=4, help_text='Taxa de juros mensal aplicada ao empréstimo', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('installments_count', models.PositiveIntegerField(help_text='Quantidade total de parcelas do empréstimo', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('iof_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de IOF calculado para o empréstimo', max_digits=15)),
                ('cet_monthly', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='CET mensal (Custo Efetivo Total)', max_digits=7)),
                ('cet_yearly', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='CET anual (Custo Efetivo Total)', max_digits=7)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor total devido considerando juros e IOF', max_digits=15)),
                ('contract_date', models.DateField(default=django.utils.timezone.localdate, help_text='Data de assinatura do contrato')),
                ('first_due_date', models.DateField(help_text='Data de vencimento da primeira parcela')),
                ('status', models.CharField(choices=[('ANALYSIS', 'Em análise'), ('APPROVED', 'Aprovado'), ('ACTIVE', 'Ativo'), ('FINISHED', 'Finalizado'), ('COLLECTION', 'Em cobrança'), ('CANCELLED', 'Cancelado')], default='ANALYSIS', help_text='Status atual do empréstimo', max_length=15)),
                ('regret_deadline', models.DateField(blank=True, help_text='Prazo legal para arrependimento (7 dias)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Observações adicionais sobre o empréstimo')),
                ('version', models.PositiveIntegerField(default=1, help_text='Controle de concorrência otimista')),
            ],
            options={
                'db_table': 'operations_loans',
                'ordering': ['-created_at'],
            },
        ),
    ]
