# Generated by Django 4.2.24 on 2025-09-24 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('customers', '0004_historicaladdress_history_user_address_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='consultant',
            field=models.ForeignKey(blank=True, help_text='Consultor responsável pelo empréstimo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='users.consultant'),
        ),
        migrations.AddField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(help_text='Cliente associado ao empréstimo', on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='installment',
            name='loan',
            field=models.ForeignKey(help_text='Empréstimo ao qual a parcela pertence', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='operations.loan'),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='consultant',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Consultor responsável pelo empréstimo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.consultant'),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Cliente associado ao empréstimo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinstallment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinstallment',
            name='loan',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Empréstimo ao qual a parcela pertence', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.loan'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['tenant_id', 'status'], name='ops_loans_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['tenant_id', 'customer'], name='ops_loans_tenant_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['tenant_id', 'contract_date'], name='ops_loans_tenant_contract_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['tenant_id', 'consultant'], name='ops_loans_t_consult_idx'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(check=models.Q(('principal_amount__gt', 0)), name='ops_loans_principal_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(check=models.Q(('interest_rate__gte', 0)), name='ops_loans_interest_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', models.F('principal_amount'))), name='ops_loans_total_gte_principal'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['tenant_id', 'loan'], name='ops_inst_tenant_loan_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['tenant_id', 'status'], name='ops_inst_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['tenant_id', 'due_date'], name='ops_inst_tenant_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'loan', 'sequence'), name='ops_inst_unique_seq_per_loan'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gt', 0)), name='ops_inst_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(check=models.Q(('principal_amount__gte', 0)), name='ops_inst_principal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(check=models.Q(('interest_amount__gte', 0)), name='ops_inst_interest_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', 0)), name='ops_inst_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(check=models.Q(('amount_paid__gte', 0)), name='ops_inst_amount_paid_non_negative'),
        ),
    ]
