name: Frontend Foundation CI

on:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
  workflow_dispatch: {}

env:
  PNPM_VERSION: 9.12.2
  NODE_VERSION: 20.17.0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: ESLint (FSD boundaries + Zustand guard)
        run: pnpm lint

  test:
    name: Vitest
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Vitest
        run: pnpm test

  contracts:
    name: Contracts (Spectral, OpenAPI Diff, Pact)
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Spectral lint (US1/US2/US3)
        run: pnpm openapi:lint

      - name: OpenAPI diff foundation spec
        run: pnpm openapi:diff

      - name: Pact consumer verification (US1/US2/US3)
        run: pnpm pact:verify

  visual-accessibility:
    name: Visual & Accessibility Gates
    runs-on: ubuntu-latest
    needs: contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Placeholder
        run: echo 'TODO: implementar execução de Storybook/Chromatic e axe-core.'

  performance:
    name: Performance Budgets
    runs-on: ubuntu-latest
    needs: contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Placeholder
        run: echo 'TODO: integrar Lighthouse e k6.'

  security:
    name: Security Checks
    runs-on: ubuntu-latest
    needs: contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Placeholder
        run: echo 'TODO: configurar Semgrep/DAST/SCA e SBOM.'
