// Auto-gerado por foundation:tokens. Não editar manualmente.
export type TenantTokenCategories = {
  foundation: Record<string, string>;
  semantic: Record<string, string>;
  component: Record<string, string>;
};

export const tenantTokens: Record<string, TenantTokenCategories> = {
  'tenant-alfa': {
    component: {
      'button.primary.bg': '#0F766E',
      'button.primary.border': '#0F766E',
      'button.primary.focus': 'rgba(15, 118, 110, 0.35)',
      'button.primary.hover': '#0C6A63',
      'button.primary.shadow': '0 1px 2px rgba(15, 23, 42, 0.08)',
      'button.primary.text': '#F0FDFA',
    },
    foundation: {
      'border.width.base': '2px',
      'border.width.hairline': '1px',
      'border.width.thick': '4px',
      'border.width.thin': '1.5px',
      'chart.1': '#0EA5E9',
      'chart.2': '#65A30D',
      'chart.3': '#22C55E',
      'chart.4': '#F97316',
      'chart.5': '#14B8A6',
      'color.background.alt': '#DCFCE7',
      'color.background.default': '#F0FDF4',
      'color.border.default': '#86EFAC',
      'color.brand.on-primary': '#F0FDFA',
      'color.brand.on-secondary': '#052E16',
      'color.brand.primary': '#0F766E',
      'color.brand.secondary': '#65A30D',
      'color.surface.default': '#FFFFFF',
      'color.surface.inverse': '#064E3B',
      'color.text.muted': '#3F624F',
      'color.text.primary': '#052E16',
      'color.text.secondary': '#1C4532',
      'font.family.mono': '"Geist Mono", "Fira Code", "SFMono-Regular", monospace',
      'font.family.sans': '"Geist Sans", "Inter", "Segoe UI", system',
      'font.lineHeight.2xl': '2rem',
      'font.lineHeight.3xl': '2.25rem',
      'font.lineHeight.4xl': '2.5rem',
      'font.lineHeight.5xl': '1.05',
      'font.lineHeight.base': '1.5rem',
      'font.lineHeight.lg': '1.75rem',
      'font.lineHeight.sm': '1.25rem',
      'font.lineHeight.xl': '1.85rem',
      'font.lineHeight.xs': '1.125rem',
      'font.size.2xl': '1.5rem',
      'font.size.3xl': '1.875rem',
      'font.size.4xl': '2.25rem',
      'font.size.5xl': '3rem',
      'font.size.base': '1rem',
      'font.size.lg': '1.125rem',
      'font.size.sm': '0.875rem',
      'font.size.xl': '1.25rem',
      'font.size.xs': '0.75rem',
      'font.weight.bold': '700',
      'font.weight.light': '300',
      'font.weight.medium': '500',
      'font.weight.regular': '400',
      'font.weight.semibold': '600',
      'layer.content': '0',
      'layer.dropdown': '1000',
      'layer.modal': '1060',
      'layer.overlay': '1040',
      'layer.popover': '1080',
      'layer.sticky': '1020',
      'layer.toast': '1100',
      'radius.full': '9999px',
      'radius.lg': '10px',
      'radius.md': '6px',
      'radius.none': '0px',
      'radius.sm': '4px',
      'radius.xl': '16px',
      'radius.xs': '2px',
      'shadow.focus': '0 0 0 3px rgba(15, 118, 110, 0.35)',
      'shadow.lg': '0 12px 20px rgba(15, 23, 42, 0.16)',
      'shadow.md': '0 4px 8px rgba(15, 23, 42, 0.12)',
      'shadow.sm': '0 1px 2px rgba(15, 23, 42, 0.08)',
      'space.0': '0rem',
      'space.1': '0.25rem',
      'space.10': '5rem',
      'space.11': '6rem',
      'space.12': '8rem',
      'space.2': '0.5rem',
      'space.3': '0.75rem',
      'space.4': '1rem',
      'space.5': '1.5rem',
      'space.6': '2rem',
      'space.7': '2.5rem',
      'space.8': '3rem',
      'space.9': '4rem',
      'transition.base': '200ms',
      'transition.fast': '150ms',
      'transition.slow': '300ms',
      'transition.timing.accelerate': 'cubic-bezier(0.4, 0, 1, 1)',
      'transition.timing.decelerate': 'cubic-bezier(0, 0, 0.2, 1)',
      'transition.timing.standard': 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
    semantic: {
      'border.default': '#86EFAC',
      'focus.ring': 'rgba(15, 118, 110, 0.35)',
      'status.danger.bg': '#B91C1C',
      'status.danger.on': '#FEF2F2',
      'status.info.bg': '#0369A1',
      'status.info.on': '#E0F2FE',
      'status.neutral.bg': '#0F172A0D',
      'status.neutral.on': '#0F172A',
      'status.success.bg': '#15803D',
      'status.success.on': '#F0FDF4',
      'status.warning.bg': '#B45309',
      'status.warning.on': '#FFFBEB',
      'surface.background': '#F0FDF4',
      'surface.background.alt': '#DCFCE7',
      'surface.card': '#FFFFFF',
      'surface.inverse': '#064E3B',
      'text.muted': '#3F624F',
      'text.primary': '#052E16',
      'text.secondary': '#1C4532',
    },
  },
  'tenant-beta': {
    component: {
      'button.primary.bg': '#7C3AED',
      'button.primary.border': '#7C3AED',
      'button.primary.focus': 'rgba(124, 58, 237, 0.35)',
      'button.primary.hover': '#6D35D3',
      'button.primary.shadow': '0 1px 2px rgba(15, 23, 42, 0.08)',
      'button.primary.text': '#F5F3FF',
    },
    foundation: {
      'border.width.base': '2px',
      'border.width.hairline': '1px',
      'border.width.thick': '4px',
      'border.width.thin': '1.5px',
      'chart.1': '#7C3AED',
      'chart.2': '#F59E0B',
      'chart.3': '#C084FC',
      'chart.4': '#38BDF8',
      'chart.5': '#F472B6',
      'color.background.alt': '#EDE9FE',
      'color.background.default': '#F5F3FF',
      'color.border.default': '#C4B5FD',
      'color.brand.on-primary': '#F5F3FF',
      'color.brand.on-secondary': '#0C4A6E',
      'color.brand.primary': '#7C3AED',
      'color.brand.secondary': '#38BDF8',
      'color.surface.default': '#FFFFFF',
      'color.surface.inverse': '#1E1B4B',
      'color.text.muted': '#6B6684',
      'color.text.primary': '#1E1B4B',
      'color.text.secondary': '#3F3D56',
      'font.family.mono': '"Geist Mono", "Fira Code", "SFMono-Regular", monospace',
      'font.family.sans': '"Geist Sans", "Inter", "Segoe UI", system',
      'font.lineHeight.2xl': '2rem',
      'font.lineHeight.3xl': '2.25rem',
      'font.lineHeight.4xl': '2.5rem',
      'font.lineHeight.5xl': '1.05',
      'font.lineHeight.base': '1.5rem',
      'font.lineHeight.lg': '1.75rem',
      'font.lineHeight.sm': '1.25rem',
      'font.lineHeight.xl': '1.85rem',
      'font.lineHeight.xs': '1.125rem',
      'font.size.2xl': '1.5rem',
      'font.size.3xl': '1.875rem',
      'font.size.4xl': '2.25rem',
      'font.size.5xl': '3rem',
      'font.size.base': '1rem',
      'font.size.lg': '1.125rem',
      'font.size.sm': '0.875rem',
      'font.size.xl': '1.25rem',
      'font.size.xs': '0.75rem',
      'font.weight.bold': '700',
      'font.weight.light': '300',
      'font.weight.medium': '500',
      'font.weight.regular': '400',
      'font.weight.semibold': '600',
      'layer.content': '0',
      'layer.dropdown': '1000',
      'layer.modal': '1060',
      'layer.overlay': '1040',
      'layer.popover': '1080',
      'layer.sticky': '1020',
      'layer.toast': '1100',
      'radius.full': '9999px',
      'radius.lg': '10px',
      'radius.md': '6px',
      'radius.none': '0px',
      'radius.sm': '4px',
      'radius.xl': '16px',
      'radius.xs': '2px',
      'shadow.focus': '0 0 0 3px rgba(124, 58, 237, 0.35)',
      'shadow.lg': '0 12px 20px rgba(15, 23, 42, 0.16)',
      'shadow.md': '0 4px 8px rgba(15, 23, 42, 0.12)',
      'shadow.sm': '0 1px 2px rgba(15, 23, 42, 0.08)',
      'space.0': '0rem',
      'space.1': '0.25rem',
      'space.10': '5rem',
      'space.11': '6rem',
      'space.12': '8rem',
      'space.2': '0.5rem',
      'space.3': '0.75rem',
      'space.4': '1rem',
      'space.5': '1.5rem',
      'space.6': '2rem',
      'space.7': '2.5rem',
      'space.8': '3rem',
      'space.9': '4rem',
      'transition.base': '200ms',
      'transition.fast': '150ms',
      'transition.slow': '300ms',
      'transition.timing.accelerate': 'cubic-bezier(0.4, 0, 1, 1)',
      'transition.timing.decelerate': 'cubic-bezier(0, 0, 0.2, 1)',
      'transition.timing.standard': 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
    semantic: {
      'border.default': '#C4B5FD',
      'focus.ring': 'rgba(124, 58, 237, 0.35)',
      'status.danger.bg': '#B91C1C',
      'status.danger.on': '#FEF2F2',
      'status.info.bg': '#0369A1',
      'status.info.on': '#E0F2FE',
      'status.neutral.bg': '#0F172A0D',
      'status.neutral.on': '#0F172A',
      'status.success.bg': '#15803D',
      'status.success.on': '#F0FDF4',
      'status.warning.bg': '#B45309',
      'status.warning.on': '#FFFBEB',
      'surface.background': '#F5F3FF',
      'surface.background.alt': '#EDE9FE',
      'surface.card': '#FFFFFF',
      'surface.inverse': '#1E1B4B',
      'text.muted': '#6B6684',
      'text.primary': '#1E1B4B',
      'text.secondary': '#3F3D56',
    },
  },
  'tenant-default': {
    component: {
      'button.primary.bg': '#1E3A8A',
      'button.primary.border': '#1E3A8A',
      'button.primary.focus': 'rgba(30, 58, 138, 0.35)',
      'button.primary.hover': '#1B4FA7',
      'button.primary.shadow': '0 1px 2px rgba(15, 23, 42, 0.08)',
      'button.primary.text': '#F8FAFC',
    },
    foundation: {
      'border.width.base': '2px',
      'border.width.hairline': '1px',
      'border.width.thick': '4px',
      'border.width.thin': '1.5px',
      'chart.1': '#2563EB',
      'chart.2': '#F97316',
      'chart.3': '#10B981',
      'chart.4': '#EC4899',
      'chart.5': '#8B5CF6',
      'color.background.alt': '#E2E8F0',
      'color.background.default': '#F8FAFC',
      'color.border.default': '#CBD5F5',
      'color.brand.on-primary': '#F8FAFC',
      'color.brand.on-secondary': '#0F172A',
      'color.brand.primary': '#1E3A8A',
      'color.brand.secondary': '#0EA5E9',
      'color.surface.default': '#FFFFFF',
      'color.surface.inverse': '#0F172A',
      'color.text.muted': '#64748B',
      'color.text.primary': '#0F172A',
      'color.text.secondary': '#475569',
      'font.family.mono': '"Geist Mono", "Fira Code", "SFMono-Regular", monospace',
      'font.family.sans': '"Geist Sans", "Inter", "Segoe UI", system',
      'font.lineHeight.2xl': '2rem',
      'font.lineHeight.3xl': '2.25rem',
      'font.lineHeight.4xl': '2.5rem',
      'font.lineHeight.5xl': '1.05',
      'font.lineHeight.base': '1.5rem',
      'font.lineHeight.lg': '1.75rem',
      'font.lineHeight.sm': '1.25rem',
      'font.lineHeight.xl': '1.85rem',
      'font.lineHeight.xs': '1.125rem',
      'font.size.2xl': '1.5rem',
      'font.size.3xl': '1.875rem',
      'font.size.4xl': '2.25rem',
      'font.size.5xl': '3rem',
      'font.size.base': '1rem',
      'font.size.lg': '1.125rem',
      'font.size.sm': '0.875rem',
      'font.size.xl': '1.25rem',
      'font.size.xs': '0.75rem',
      'font.weight.bold': '700',
      'font.weight.light': '300',
      'font.weight.medium': '500',
      'font.weight.regular': '400',
      'font.weight.semibold': '600',
      'layer.content': '0',
      'layer.dropdown': '1000',
      'layer.modal': '1060',
      'layer.overlay': '1040',
      'layer.popover': '1080',
      'layer.sticky': '1020',
      'layer.toast': '1100',
      'radius.full': '9999px',
      'radius.lg': '10px',
      'radius.md': '6px',
      'radius.none': '0px',
      'radius.sm': '4px',
      'radius.xl': '16px',
      'radius.xs': '2px',
      'shadow.focus': '0 0 0 3px rgba(30, 58, 138, 0.35)',
      'shadow.lg': '0 12px 20px rgba(15, 23, 42, 0.16)',
      'shadow.md': '0 4px 8px rgba(15, 23, 42, 0.12)',
      'shadow.sm': '0 1px 2px rgba(15, 23, 42, 0.08)',
      'space.0': '0rem',
      'space.1': '0.25rem',
      'space.10': '5rem',
      'space.11': '6rem',
      'space.12': '8rem',
      'space.2': '0.5rem',
      'space.3': '0.75rem',
      'space.4': '1rem',
      'space.5': '1.5rem',
      'space.6': '2rem',
      'space.7': '2.5rem',
      'space.8': '3rem',
      'space.9': '4rem',
      'transition.base': '200ms',
      'transition.fast': '150ms',
      'transition.slow': '300ms',
      'transition.timing.accelerate': 'cubic-bezier(0.4, 0, 1, 1)',
      'transition.timing.decelerate': 'cubic-bezier(0, 0, 0.2, 1)',
      'transition.timing.standard': 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
    semantic: {
      'border.default': '#CBD5F5',
      'focus.ring': 'rgba(30, 58, 138, 0.35)',
      'status.danger.bg': '#B91C1C',
      'status.danger.on': '#FEF2F2',
      'status.info.bg': '#0369A1',
      'status.info.on': '#E0F2FE',
      'status.neutral.bg': '#0F172A0D',
      'status.neutral.on': '#0F172A',
      'status.success.bg': '#15803D',
      'status.success.on': '#F0FDF4',
      'status.warning.bg': '#B45309',
      'status.warning.on': '#FFFBEB',
      'surface.background': '#F8FAFC',
      'surface.background.alt': '#E2E8F0',
      'surface.card': '#FFFFFF',
      'surface.inverse': '#0F172A',
      'text.muted': '#64748B',
      'text.primary': '#0F172A',
      'text.secondary': '#475569',
    },
  }
} as const;

export const tenantVersions: Record<string, string> = {
  'tenant-alfa': '1.0.0',
  'tenant-beta': '1.0.0',
  'tenant-default': '1.0.0'
} as const;

export const tenantIds: Record<string, string> = {
  'tenant-alfa': '00000000-0000-0000-0000-000000000001',
  'tenant-beta': '00000000-0000-0000-0000-000000000002',
  'tenant-default': '00000000-0000-0000-0000-000000000000'
} as const;

