apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-foundation-prometheus-config
  namespace: foundation
  labels:
    app: frontend-foundation
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      evaluation_interval: 30s
    scrape_configs:
      - job_name: frontend-foundation
        honor_labels: true
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: frontend-foundation
          - source_labels: [__meta_kubernetes_pod_phase]
            action: keep
            regex: Running
        metric_relabel_configs:
          - source_labels: [container]
            action: keep
            regex: frontend|web
          - source_labels: [__name__]
            regex: 'container_(cpu_usage_seconds_total|memory_usage_bytes).*'
            action: keep
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-foundation-metrics
  namespace: foundation
  labels:
    app: frontend-foundation
spec:
  selector:
    app: frontend-foundation
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-foundation
  namespace: foundation
  labels:
    app: frontend-foundation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-foundation
  template:
    metadata:
      labels:
        app: frontend-foundation
    spec:
      serviceAccountName: frontend-foundation
      containers:
        - name: frontend
          image: ghcr.io/iabank/frontend-foundation:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
        - name: metrics-sidecar
          image: prom/prometheus:v2.53.0
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time=2h"
            - "--web.listen-address=:9090"
            - "--log.level=info"
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
              readOnly: true
            - name: prometheus-data
              mountPath: /prometheus
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: prometheus-config
          configMap:
            name: frontend-foundation-prometheus-config
        - name: prometheus-data
          emptyDir:
            sizeLimit: 1Gi
