apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-foundation
  namespace: foundation
  labels:
    app: frontend-foundation
    release: prometheus-operator
spec:
  namespaceSelector:
    matchNames:
      - foundation
  selector:
    matchLabels:
      app: frontend-foundation
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
