# Generated by Django 4.2.11 on 2025-10-23 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiContractArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('openapi', 'OpenAPI'), ('pact-consumer', 'Pact Consumer'), ('pact-provider', 'Pact Provider')], max_length=32)),
                ('version', models.CharField(max_length=32)),
                ('checksum', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=255)),
                ('breaking_change', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('type', 'version', 'path')},
            },
        ),
        migrations.CreateModel(
            name='ContractDiffReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(choices=[('spectral', 'Spectral'), ('openapi-diff', 'OpenAPI Diff'), ('pact-cli', 'Pact CLI')], max_length=32)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('warn', 'Warning'), ('fail', 'Fail')], max_length=16)),
                ('summary', models.TextField()),
                ('logged_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diff_reports', to='contracts.apicontractartifact')),
            ],
            options={
                'ordering': ('-logged_at', '-created_at'),
            },
        ),
    ]
