# Generated by Django 4.2.26 on 2025-11-27 19:54

import backend.apps.tenancy.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0029_alter_budgetratelimit_managers_and_more'),
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accountcategory',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='address',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='bankaccount',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='consultant',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contract',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='creditlimit',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='financialtransaction',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='installment',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='loan',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='supplier',
            managers=[
                ('objects', backend.apps.tenancy.managers.TenantManager()),
            ],
        ),
        migrations.AlterField(
            model_name='accountcategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='address',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='creditlimit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='creditlimit',
            unique_together={('tenant', 'bank_account')},
        ),
    ]
